# install.packages("BiocManager")
# BiocManager::install("minfi", ask = T)
# BiocManager::install("limma", ask = T)
# BiocManager::install("IlluminaHumanMethylation450kmanifest", ask = T)
# BiocManager::install("IlluminaHumanMethylationEPICmanifest", ask = T)