library(minfi)
args = commandArgs(trailingOnly = T)
analysis_package <- "IlluminaHumanMethylationEPICmanifest"
library(analysis_package, character.only = TRUE)


#' Get Updated Metadata
#' @param metadata A data frame containing the meta data, converting the group factor to autogenerated
#' @return A updated metadata
get_updated_metadata <- function(metadata)
{
    # Convert 'Group' to factor with automatically generated levels
    metadata$conditions <- factor(metadata$conditions, 
                                    levels = unique(metadata$conditions), 
                                    labels = paste0("conditions", seq_along(unique(metadata$conditions))))
    return (metadata);
}

# Get B-values
# @param metadata A data frame containing the meta data, including the paths to the IDAT files.
# @param opts A list containing options for preprocessing the IDAT files. The list should include:
# @return A matrix of B-values obtained after preprocessing the IDAT files.
get_b_values <- function(metadata, opts) {
    # Read IDAT files
    RGset <- read.metharray(metadata$path, extended = TRUE)

    preprocess_method = opts$pp
    if (preprocess_method == "preprocessSWAN") {
        betaSet <- preprocessSWAN(RGset)
    } else if (preprocess_method == "preprocessQuantile") {
        betaSet <- preprocessQuantile(RGset)
    } else if (preprocess_method == "preprocessNoob") {
        betaSet <- preprocessNoob(RGset)
    } else if (preprocess_method == "preprocessRaw") {
        betaSet <- preprocessRaw(RGset)
    } else {
        betaSet <- preprocessIllumina(RGset)
    }
    # get m_ values
    b_values <- getBeta(betaSet)
    return(b_values)
}

#' compress result
#' This function compresses the results file into a gzipped format.
#' @param results A data frame containing the results to be compressed.
#' @param gzfile_path The path where the gzipped file will be saved.
#' @return None
get_compressed_result <- function(results, gzfile_path) {
    gz_con <- gzfile(gzfile_path, "wt")
    write.csv(results, gz_con, row.names = TRUE)
    close(gz_con)
}